version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks: 
      - minha-rede
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    networks: 
      - minha-rede 
networks: 
  minha-rede:
    driver: bridge





